pull in makepath from shunit2 branch and cleanup

diff --git a/makepath b/makepath
--- a/makepath
+++ b/makepath
@@ -1,21 +1,29 @@
 # makepath
 # given a pathname, create all components in that pathname as directories.
 
-die() { echo "$*" >&2; exit 1; }
-warn() { echo "$*" >&2; }
+warn() { printf "$*\n" >&2; }
 
 function make-one-path() {
 
-  { [ -b "$@" ] || [ -c "$@" ] || [ -f "$@" ] || [ -p "$@" ]; } &&
-    warn "$FUNCNAME: cannot create directory \`"$@"': File exists"
+  [ -d "$@" ] && return 0
 
-  [ -e "$@" ] && return 0
-  makepath $(dirname "$@") &&
-    mkdir "$@"
+  if [ -b "$@" ] || [ -c "$@" ] || [ -f "$@" ] || [ -p "$@" ]; then
+    warn "makepath: cannot create directory \`$@': File exists"
+    return 1
+  fi
+
+  if ! makepath $(dirname "$@"); then
+    warn "makepath: cannot create directory \`$@': Permission denied"
+    return 1
+  fi
+
+  mkdir "$@"
 }
 
+nerrs=0
 function makepath() {
   for i in "$@"; do
-    make-one-path "$i"
+    make-one-path "$i" || (( nerrs += 1 ))
   done
+  return $nerrs
 }
